# Generated by Django 5.0.1 on 2025-01-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="电子邮箱"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="名字"),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="用户所属的组。一个用户将获得其所属组的所有权限。",
                related_name="custom_user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="用户组",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="指定是否应该将此用户视为活动用户。取消选择此项而不是删除帐户。",
                verbose_name="激活状态",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False, help_text="指定用户是否可以登录到这个管理站点。", verbose_name="工作人员状态"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False, help_text="指定该用户具有所有权限而无需明确分配它们。", verbose_name="超级管理员状态"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后登录"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="姓氏"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="为该用户特别指定的权限。",
                related_name="custom_user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="用户权限",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "该用户名已存在。"},
                help_text="必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。",
                max_length=150,
                unique=True,
                verbose_name="用户名",
            ),
        ),
    ]
