# Generated by Django 5.0.1 on 2025-01-21 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trade", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(verbose_name="分销等级")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="佣金金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待结算"),
                            ("settled", "已结算"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="结算状态",
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结算时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分销商",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="trade.order",
                        verbose_name="关联订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "佣金记录",
                "verbose_name_plural": "佣金记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DistributionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(1, "一级分销"), (2, "二级分销"), (3, "三级分销")],
                        verbose_name="分销等级",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="例如：0.10 表示 10%",
                        max_digits=4,
                        verbose_name="佣金比例",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "分销规则",
                "verbose_name_plural": "分销规则",
                "ordering": ["level"],
                "unique_together": {("level",)},
            },
        ),
        migrations.CreateModel(
            name="DistributorStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="总销售额"
                    ),
                ),
                (
                    "total_commission",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="总佣金"
                    ),
                ),
                ("team_size", models.IntegerField(default=0, verbose_name="团队人数")),
                ("order_count", models.IntegerField(default=0, verbose_name="订单数")),
                (
                    "last_order_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后订单时间"),
                ),
                (
                    "distributor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分销商",
                    ),
                ),
            ],
            options={
                "verbose_name": "分销统计",
                "verbose_name_plural": "分销统计",
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="提现金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100, verbose_name="银行名称")),
                ("bank_account", models.CharField(max_length=100, verbose_name="银行账号")),
                (
                    "account_holder",
                    models.CharField(max_length=100, verbose_name="开户人"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "handled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分销商",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
            ],
            options={
                "verbose_name": "提现申请",
                "verbose_name_plural": "提现申请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WithdrawalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "通过"),
                            ("reject", "拒绝"),
                            ("complete", "完成打款"),
                        ],
                        max_length=20,
                        verbose_name="审核动作",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="审核时间"),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "withdrawal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="distributor.withdrawal",
                        verbose_name="提现申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "提现审核记录",
                "verbose_name_plural": "提现审核记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
