# Generated by Django 5.0.1 on 2025-01-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distributor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("daily", "日报"), ("weekly", "周报"), ("monthly", "月报")],
                        max_length=10,
                        verbose_name="统计周期",
                    ),
                ),
                ("date", models.DateField(verbose_name="统计日期")),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总销售额"
                    ),
                ),
                (
                    "total_commission",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总佣金"
                    ),
                ),
                ("order_count", models.IntegerField(verbose_name="订单数")),
                ("distributor_count", models.IntegerField(verbose_name="分销商数")),
                ("new_distributor_count", models.IntegerField(verbose_name="新增分销商数")),
                (
                    "active_distributor_count",
                    models.IntegerField(verbose_name="活跃分销商数"),
                ),
                (
                    "withdrawal_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="提现金额"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "分销报表",
                "verbose_name_plural": "分销报表",
                "ordering": ["-date", "period"],
                "unique_together": {("period", "date")},
            },
        ),
    ]
